// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.datatypes.hardware_info;

/**
 * What kind of data the tracker supports
 */
@SuppressWarnings("unused")
public final class TrackerDataSupport {
  private TrackerDataSupport() { }
  public static final int ROTATION = 0;
  public static final int FLEX_RESISTANCE = 1;
  public static final int FLEX_ANGLE = 2;

  public static final String[] names = { "ROTATION", "FLEX_RESISTANCE", "FLEX_ANGLE", };

  public static String name(int e) { return names[e]; }
}

