// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class ChangeProfileRequestT {
  private String profileName;
  private String type;

  public String getProfileName() { return profileName; }

  public void setProfileName(String profileName) { this.profileName = profileName; }

  public String getType() { return type; }

  public void setType(String type) { this.type = type; }


  public ChangeProfileRequestT() {
    this.profileName = null;
    this.type = null;
  }
}

