// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class ChangeProfileRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ChangeProfileRequest {
        __init(_i, _bb)
        return this
    }
    val profileName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val profileNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun profileNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val type : String?
        get() {
            val o = __offset(6)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val typeAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun typeInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsChangeProfileRequest(_bb: ByteBuffer): ChangeProfileRequest = getRootAsChangeProfileRequest(_bb, ChangeProfileRequest())
        @JvmStatic
        fun getRootAsChangeProfileRequest(_bb: ByteBuffer, obj: ChangeProfileRequest): ChangeProfileRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createChangeProfileRequest(builder: FlatBufferBuilder, profileNameOffset: Int, typeOffset: Int) : Int {
            builder.startTable(2)
            addType(builder, typeOffset)
            addProfileName(builder, profileNameOffset)
            return endChangeProfileRequest(builder)
        }
        @JvmStatic
        fun startChangeProfileRequest(builder: FlatBufferBuilder) = builder.startTable(2)
        @JvmStatic
        fun addProfileName(builder: FlatBufferBuilder, profileName: Int) = builder.addOffset(0, profileName, 0)
        @JvmStatic
        fun addType(builder: FlatBufferBuilder, type: Int) = builder.addOffset(1, type, 0)
        @JvmStatic
        fun endChangeProfileRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
