// automatically generated by the FlatBuffers compiler, do not modify

/**
 * What kind of data the tracker supports
 */
export enum TrackerDataSupport {
  ROTATION = 0,
  FLEX_RESISTANCE = 1,
  FLEX_ANGLE = 2
}
