// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.datatypes.hardware_info

/**
 * What kind of data the tracker supports
 */
@Suppress("unused")
class TrackerDataSupport private constructor() {
    companion object {
        const val ROTATION: UByte = 0u
        const val FLEXRESISTANCE: UByte = 1u
        const val FLEXANGLE: UByte = 2u
        val names : Array<String> = arrayOf("ROTATION", "FLEX_RESISTANCE", "FLEX_ANGLE")
        @JvmStatic
        fun name(e: Int) : String = names[e]
    }
}
